name: Build and Deploy Inventory Tracker

on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Environment Check
        run: |
          whoami
          java -version
          mvn -version
          
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build with Maven (Prod Profile)
        # Uses the Maven installation already on your server
        run: mvn clean package -Pprod -DskipTests

      - name: Copy Jar to Deployment Folder
        run: |
          sudo mkdir -p /opt/inventory-tracker
          sudo cp target/MO-Inventory-tracker-0.0.1-SNAPSHOT.jar /opt/inventory-tracker/inventory-tracker-0.0.1-SNAPSHOT.jar

      - name: Restart Service
        run: |
          sudo systemctl restart inventory-tracker.service
          
      - name: Check Status
        run: |
          systemctl status inventory-tracker.service --no-pager
